[package]
name = "tpp-keeper"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tpp-keeper"
path = "src/main.rs"

[dependencies]
tpp-common = { path = "../common" }
tpp-db = { path = "../db" }

tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { workspace = true }
serde_json = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
solana-commitment-config = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
