// ─────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by contracts/scripts/devnet-init.ts — do NOT edit manually
// Re-run `npx ts-node -P tsconfig.json scripts/devnet-init.ts` to update.
// ─────────────────────────────────────────────────────────────────────────

export const PROGRAM_ID = '9iUeMGw14CaAiASMUruBMWRR5j7HcEXwthuN5pDAo3Qf';
export const USDC_MINT = 'GgUG99UGb2fz5vYHRGMW9yfMgtczEVNjEUhW3Vyov6yr';
export const CONFIG_PDA = 'ErhxXL9VUUBeEPu1L62hpAZJ7oGrqhGabiYZDn6g99TL';
export const FEE_TREASURY_PDA = 'CBa5y6AetSs6VpWDxgJbj9Vt8EnHiDhVhZQUSmK8Cgoz';

export interface MarketDef {
  label: string;
  feedId: string;   // 32-byte Pyth price feed ID (hex, no 0x prefix)
  oracle: string;   // devnet mock oracle account pubkey
}

export const MARKETS: MarketDef[] = [
  { label: 'BTC/USD', feedId: 'e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43', oracle: 'Cm3EZjU8D5MHDP6tGSZBGXEvz1rXVfAHydoepFB5hQ5t' },
  { label: 'ETH/USD', feedId: 'ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace', oracle: '7VivVtfizWqtzyoBvsp6HS1BkEJQd26CV1cjK69ezGNh' },
  { label: 'SOL/USD', feedId: 'ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d', oracle: '68utR51CRAH7hCHx5GS4sZvUCL4pe6h4uS1GT1t2bXkz' },
];
